#pragma kernel CSMain

RWTexture2D<float4> Result;
Texture2D<float4> Source;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint width, height;
    Result.GetDimensions(width, height);

    if (id.x >= width || id.y >= height)
        return;

    float2 uv = float2(id.xy) / float2(width, height);

    float4 col = Source[id.xy];

    // Example effect: invert
    col.rgb = 1.0 - col.rgb;

    Result[id.xy] = float4(1,0,0,1);
}
